#!/bin/sh

start() {
  echo "Starting GPIO-RW ..."
  insmod /lib/modules/$(uname -r)/updates/gpio_rw.ko.xz
}

stop() {
  echo "Stopping GPIO-RW ..."
  rmmod gpio_rw
}

restart() {
  stop
  start
}

case $1 in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac

exit 0

