#!/bin/sh

start() {
  echo "Starting WiFi ..."
  wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
  dhcpcd wlan0
}

stop() {
  echo "Stopping WiFi ..."
  killall wpa_supplicant
}

restart() {
  stop
  start
}

case $1 in
  start)
    #start
    ;;
  stop)
    #stop
    ;;
  restart|reload)
    #restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac

exit 0

